import type { BusinessInfo, ServiceItem, ReviewItem, GalleryItem } from './types';

export const BUSINESS_INFO: BusinessInfo = {
  name: 'Ultimate Auto Detailing',
  tagline: 'ULTIMATE SHINE. EXCEPTIONAL DETAIL.',
  location: 'Los Angeles, California',
  phone: '440-726-4593',
  phoneRaw: '4407264593',
  email: 'ultimate1cardetailingsolutions@gmail.com',
  facebook: 'https://www.facebook.com/UltimateCarDetailingSolutions',
  instagram: 'https://www.instagram.com/ultimateautodetailing.us',
};

export const CLOUDINARY_ASSETS = {
  logo: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906834/ugfdytqwdvdqwvq.jpg',
  beforeAfter: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/ba.jpg',
  heroBanner: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bhiv146vdd.jpg',
  showcaseHero: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906833/huqwdebvyugjwde_jhwq.jpg',
  aboutDetail: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bhgewqgfdytqfd.jpg',
  finalCta: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bbbhhhuuu.jpg',
};

export const SERVICES: ServiceItem[] = [
  {
    id: 'full-auto-detailing',
    name: 'Full Auto Detailing',
    summary: 'Comprehensive interior and exterior rejuvenation tailored for high-end automotive presentation.',
    features: [
      'Complete exterior multi-stage wash & decontaminating treatment',
      'Thorough cabin vacuuming, conditioning, and sanitization',
      'Paint cleansing, glass clarification, and tire dressing',
    ],
    icon: 'Sparkles',
  },
  {
    id: 'deep-interior-cleaning',
    name: 'Deep Interior Cleaning',
    summary: 'Intensive restoration of cabin surfaces, upholstery, leather, and intricate interior compartments.',
    features: [
      'Delicate leather cleansing, conditioning, and matte finishing',
      'Deep carpet and fabric fiber extraction cleaning',
      'Air vent, console, dashboard, and crevice detailing',
    ],
    icon: 'Armchair',
  },
  {
    id: 'exterior-wash-wax',
    name: 'Exterior Wash & Wax',
    summary: 'Hand-washing procedure followed by a protective wax layer to enhance depth and mirror gloss.',
    features: [
      'Gentle hand wash with pH-balanced car care solutions',
      'Surface contaminant removal and streak-free rinse',
      'Hand-applied protective wax for gloss enhancement',
    ],
    icon: 'Droplets',
  },
  {
    id: 'paint-correction',
    name: 'Paint Correction',
    summary: 'Precision machine polishing process designed to diminish surface swirl marks and micro-scratches.',
    features: [
      'Detailed paint inspection under high-intensity inspection lighting',
      'Multi-stage rotary and dual-action machine compounding & polishing',
      'Restoration of true optical clarity, depth, and gloss reflection',
    ],
    icon: 'Disc',
  },
  {
    id: 'paint-protection',
    name: 'Paint Protection',
    summary: 'Protective barriers engineered to preserve exterior paint from environmental contaminants.',
    features: [
      'Advanced sealant application for sustained surface resilience',
      'Protection against road debris fallout, UV rays, and water spots',
      'Hydrophobic properties for effortless subsequent maintenance',
    ],
    icon: 'Shield',
  },
  {
    id: 'tire-rim-shine',
    name: 'Tire & Rim Shine',
    summary: 'Deep decontamination and meticulous finishing for wheels, brake caliper faces, and tire walls.',
    features: [
      'Removal of embedded brake dust and road grime from rim barrels',
      'Non-sling, deep satin-gloss tire dressing application',
      'Wheel face decontamination and polished alloy finish',
    ],
    icon: 'CircleDot',
  },
  {
    id: 'ceramic-coating',
    name: 'Ceramic Coating',
    summary: 'Semi-permanent hydrophobic protective coating delivering deep gloss and durable paint shielding.',
    features: [
      'Paint preparation and alcohol panel wipe for optimal bonding',
      'High-grade ceramic liquid coating application to painted surfaces',
      'Extreme water beading and prolonged gloss retention',
    ],
    icon: 'Gem',
  },
];

export const SAMPLE_REVIEWS: ReviewItem[] = [
  {
    id: 'sample-rev-1',
    author: 'Vehicle Owner (Los Angeles)',
    vehicle: 'Luxury Coupe',
    rating: 5,
    text: 'The paint finish looks remarkably deep and glossy. Every edge and door jamb was thoroughly addressed with great care.',
    isSample: true,
  },
  {
    id: 'sample-rev-2',
    author: 'Vehicle Owner (Beverly Hills)',
    vehicle: 'Exotic Sports Car',
    rating: 5,
    text: 'Outstanding attention to detail on the leather cabin and wheel finish. Professional demeanor and great communication throughout.',
    isSample: true,
  },
  {
    id: 'sample-rev-3',
    author: 'Vehicle Owner (Santa Monica)',
    vehicle: 'Performance SUV',
    rating: 5,
    text: 'Exterior wash, polish, and ceramic coating brought back a true mirror-like reflection. Very satisfied with the presentation.',
    isSample: true,
  },
  {
    id: 'sample-rev-4',
    author: 'Vehicle Owner (Pasadena)',
    vehicle: 'Grand Tourer',
    rating: 5,
    text: 'Clean interior rejuvenation with no greasy residues. The metallic paint pops under sunlight just as expected.',
    isSample: true,
  },
];

export const ALL_GALLERY_IMAGES: GalleryItem[] = [
  {
    id: 'gal-ba',
    title: 'Before & After Detailing Transformation',
    category: 'Transformation',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/ba.jpg',
    alt: 'Before and after automotive paint and surface detailing transformation',
    description: 'Direct comparison demonstrating surface correction, oxidation removal, and renewed gloss depth.',
  },
  {
    id: 'gal-1',
    title: 'Exotic Sports Car Studio Finish',
    category: 'Exotics & Luxury',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906833/huqwdebvyugjwde_jhwq.jpg',
    alt: 'Luxury vehicle with immaculate paint gloss and reflection under studio lighting',
    description: 'Precision detailing highlighting vehicle contours and pristine paint reflection.',
  },
  {
    id: 'gal-2',
    title: 'Deep Gloss Paint Clarification',
    category: 'Paint Correction',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bhgewqgfdytqfd.jpg',
    alt: 'Automotive paint reflection and swirl-free clear coat finish',
    description: 'High-optical clarity clear coat after multi-stage machine compounding.',
  },
  {
    id: 'gal-3',
    title: 'Luxury Vehicle Exterior Treatment',
    category: 'Exotics & Luxury',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bbbhhhuuu.jpg',
    alt: 'Immaculately washed and sealed luxury vehicle in studio',
    description: 'Comprehensive exterior hand wash, clay bar decontamination, and hydrophobic sealant.',
  },
  {
    id: 'gal-4',
    title: 'Studio Surface Inspection',
    category: 'Paint Correction',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906839/ygdvgvdhiqwhgdqw.jpg',
    alt: 'Automotive surface detailing inspection under high contrast lighting',
    description: 'Meticulous inspection of surface clear coat to ensure zero swirl marks.',
  },
  {
    id: 'gal-5',
    title: 'Precision Wheel & Rim Dressing',
    category: 'Wheels & Accents',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906299/gyu_gqvdytqdbd.jpg',
    alt: 'Detailed alloy wheels with deep satin tire dressing and brake dust decontamination',
    description: 'Complete wheel decontamination and long-lasting non-sling tire finish.',
  },
  {
    id: 'gal-6',
    title: 'Clean Emblem & Crevice Refinement',
    category: 'Exterior Detail',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906298/ghgjkiniuhgvedbv6765.jpg',
    alt: 'Close-up of clean vehicle emblem, grill, and trim detailing',
    description: 'Precision brush detailing across emblems, vents, and panel gaps.',
  },
  {
    id: 'gal-7',
    title: 'Performance Sedan Paint Elevation',
    category: 'Exotics & Luxury',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906838/wqwqdqdqdw1.jpg',
    alt: 'Detailed performance vehicle showcasing deep mirror-like paint finish',
    description: 'Enhanced depth and color saturation on high-performance automotive paint.',
  },
  {
    id: 'gal-8',
    title: 'Full Exterior Wash & Polish',
    category: 'Exterior Detail',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906838/wdwqdqwqoioi9.jpg',
    alt: 'Freshly washed and hand-waxed luxury vehicle',
    description: 'Streak-free rinse followed by polymer gloss enhancement.',
  },
  {
    id: 'gal-9',
    title: 'High-Gloss Clear Coat Reflection',
    category: 'Paint Correction',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906834/sdfghjkpie3que.jpg',
    alt: 'Detailed vehicle side profile with mirror reflection of surroundings',
    description: 'Smooth glass-like finish achieved through meticulous pad and compound selection.',
  },
  {
    id: 'gal-10',
    title: 'Luxury Vehicle Delivery Stance',
    category: 'Exotics & Luxury',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906834/jcole.jpg',
    alt: 'Completed vehicle detailing project ready for client presentation',
    description: 'Turnkey vehicle presentation displaying refined road stance and rich gloss.',
  },
  {
    id: 'gal-11',
    title: 'Hydrophobic Surface Shielding',
    category: 'Paint Protection',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906300/hudui_iueoijiodoiqjdqdoiieiekjne.jpg',
    alt: 'Automotive paint protection and ceramic coating shielding',
    description: 'Durable barrier guarding vehicle finish against environmental exposure.',
  },
  {
    id: 'gal-12',
    title: 'Intricate Trim & Grill Preservation',
    category: 'Exterior Detail',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906299/hqwgdq.jpg',
    alt: 'Clean front grill, headlights, and front bumper detailing',
    description: 'Bug splatter, road grime, and fallout extraction with delicate safe chemicals.',
  },
  {
    id: 'gal-13',
    title: 'Deep Cabin & Upholstery Cleansing',
    category: 'Interior Detail',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906298/dqwdwqdjhu.jpg',
    alt: 'Pristine interior vehicle detailing with restored cabin textures',
    description: 'Thorough extraction, leather conditioning, and clean matte finish across cabin.',
  },
  {
    id: 'gal-14',
    title: 'Reflective Body Line Detailing',
    category: 'Paint Correction',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906297/daewfse.jpg',
    alt: 'Sleek body contours with sharp studio light reflections',
    description: 'Polished body curves capturing crisp reflections without distortion.',
  },
  {
    id: 'gal-15',
    title: 'Restored Dark Automotive Finish',
    category: 'Paint Correction',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906283/bhuuusservlkne.jpg',
    alt: 'Deep black vehicle paintwork restored to mirror shine',
    description: 'Eliminating micro-marring to unlock obsidian-level black paint depth.',
  },
  {
    id: 'gal-16',
    title: 'Precision Panel Alignment & Wax',
    category: 'Exterior Detail',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bhhjikiuh.jpg',
    alt: 'Vehicle rear quarter panel and glass with crystal clear finish',
    description: 'Flawless panel edges and streak-free treated automotive glass.',
  },
  {
    id: 'gal-17',
    title: 'Showroom Detail Finish',
    category: 'Exotics & Luxury',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906281/123456765.jpg',
    alt: 'Complete exterior and interior automotive detailing in Los Angeles',
    description: 'Exemplary craftsmanship showcasing why vehicle owners choose Ultimate Auto Detailing.',
  },
  {
    id: 'gal-18',
    title: 'Panoramic Studio Presentation',
    category: 'Exotics & Luxury',
    image: 'https://res.cloudinary.com/fzobzdco/image/upload/v1788906282/bhiv146vdd.jpg',
    alt: 'Wide cinematic view of detailed vehicle under studio illumination',
    description: 'Wide composition celebrating clean automotive architecture.',
  },
];
